"""
Run this from your sec-edgar-mcp project root:
    python fix_repo.py

It rewrites every file with correct newlines.
"""
import os

files = {}

files["requirements.txt"] = "mcp[cli]>=1.0.0\nhttpx>=0.27.0\npydantic>=2.0.0\npython-dotenv>=1.0.0\n"

files[".env.example"] = (
    "# Required: SEC EDGAR User-Agent header\n"
    "# Format: appname your-email@example.com\n"
    "# See: https://www.sec.gov/os/accessing-edgar-data\n"
    "SEC_USER_AGENT=sec-edgar-mcp your-email@example.com\n"
)

files["pyproject.toml"] = (
    '[build-system]\n'
    'requires = ["hatchling"]\n'
    'build-backend = "hatchling.build"\n'
    '\n'
    '[project]\n'
    'name = "sec-edgar-mcp"\n'
    'version = "0.1.0"\n'
    'description = "MCP server for querying live SEC EDGAR financial data"\n'
    'readme = "README.md"\n'
    'requires-python = ">=3.11"\n'
    'license = { text = "MIT" }\n'
    'keywords = ["mcp", "sec", "edgar", "finance", "llm", "claude"]\n'
    '\n'
    'dependencies = [\n'
    '    "mcp[cli]>=1.0.0",\n'
    '    "httpx>=0.27.0",\n'
    '    "pydantic>=2.0.0",\n'
    '    "python-dotenv>=1.0.0",\n'
    ']\n'
    '\n'
    '[project.scripts]\n'
    'sec-edgar-mcp = "sec_edgar_mcp.server:main"\n'
    '\n'
    '[tool.hatch.build.targets.wheel]\n'
    'packages = ["src/sec_edgar_mcp"]\n'
    '\n'
    '[project.optional-dependencies]\n'
    'dev = [\n'
    '    "pytest>=8.0.0",\n'
    '    "pytest-asyncio>=0.23.0",\n'
    ']\n'
)

files["src/sec_edgar_mcp/__init__.py"] = '"""SEC EDGAR MCP Server."""\n'

files["src/sec_edgar_mcp/__main__.py"] = (
    'from .server import main\n'
    '\n'
    'if __name__ == "__main__":\n'
    '    main()\n'
)

files["src/sec_edgar_mcp/edgar_client.py"] = (
    '"""\n'
    'SEC EDGAR API client.\n'
    'Handles all HTTP communication with the SEC public EDGAR endpoints.\n'
    '"""\n'
    '\n'
    'import os\n'
    'import httpx\n'
    'from typing import Optional\n'
    'from dotenv import load_dotenv\n'
    '\n'
    'load_dotenv()\n'
    '\n'
    '_user_agent = os.getenv("SEC_USER_AGENT", "sec-edgar-mcp your-email@example.com")\n'
    '\n'
    'HEADERS = {\n'
    '    "User-Agent": _user_agent,\n'
    '    "Accept-Encoding": "gzip, deflate",\n'
    '}\n'
    '\n'
    'BASE_URL = "https://data.sec.gov"\n'
    '\n'
    '\n'
    'async def get_json(url: str, params: Optional[dict] = None) -> dict:\n'
    '    """Generic async GET request returning parsed JSON."""\n'
    '    async with httpx.AsyncClient(headers=HEADERS, timeout=30.0) as client:\n'
    '        response = await client.get(url, params=params)\n'
    '        response.raise_for_status()\n'
    '        return response.json()\n'
    '\n'
    '\n'
    'async def fetch_submissions(cik: str) -> dict:\n'
    '    """Fetch all submission metadata for a company by CIK."""\n'
    '    padded_cik = cik.zfill(10)\n'
    '    url = f"{BASE_URL}/submissions/CIK{padded_cik}.json"\n'
    '    return await get_json(url)\n'
    '\n'
    '\n'
    'async def fetch_company_concept(cik: str, taxonomy: str, tag: str) -> dict:\n'
    '    """Fetch a single XBRL concept across all filings."""\n'
    '    padded_cik = cik.zfill(10)\n'
    '    url = f"{BASE_URL}/api/xbrl/companyconcept/CIK{padded_cik}/{taxonomy}/{tag}.json"\n'
    '    return await get_json(url)\n'
    '\n'
    '\n'
    'async def search_company_by_name(name: str) -> list[dict]:\n'
    '    """Search for companies by name using EDGAR full-text search."""\n'
    '    url = "https://efts.sec.gov/LATEST/search-index"\n'
    '    params = {"q": f\'"{name}"\', "dateRange": "custom", "forms": "10-K"}\n'
    '    async with httpx.AsyncClient(headers=HEADERS, timeout=30.0) as client:\n'
    '        response = await client.get(url, params=params)\n'
    '        response.raise_for_status()\n'
    '        data = response.json()\n'
    '    hits = data.get("hits", {}).get("hits", [])\n'
    '    seen = {}\n'
    '    for hit in hits:\n'
    '        src = hit.get("_source", {})\n'
    '        entity = src.get("entity_name", "")\n'
    '        cik = src.get("file_num", "") or src.get("entity_id", "")\n'
    '        if entity and entity not in seen:\n'
    '            seen[entity] = {"name": entity, "cik": cik}\n'
    '    return list(seen.values())[:10]\n'
    '\n'
    '\n'
    'async def get_cik_from_ticker(ticker: str) -> Optional[str]:\n'
    '    """Resolve a stock ticker to a CIK using SEC company_tickers.json."""\n'
    '    url = "https://www.sec.gov/files/company_tickers.json"\n'
    '    data = await get_json(url)\n'
    '    ticker_upper = ticker.upper()\n'
    '    for _, company in data.items():\n'
    '        if company.get("ticker", "").upper() == ticker_upper:\n'
    '            return str(company["cik_str"])\n'
    '    return None\n'
)

files["src/sec_edgar_mcp/server.py"] = (
    '"""\n'
    'SEC EDGAR MCP Server\n'
    'Exposes four tools over MCP so any MCP-compatible client\n'
    'can query live SEC EDGAR data.\n'
    '"""\n'
    '\n'
    'from mcp.server.fastmcp import FastMCP\n'
    'from .tools import search_company, get_filing, get_financials, compare_filings\n'
    '\n'
    'mcp = FastMCP("sec-edgar-mcp")\n'
    '\n'
    '\n'
    '@mcp.tool(\n'
    '    name="search_company",\n'
    '    description="Resolve a company name or ticker to its SEC CIK identifier.",\n'
    ')\n'
    'async def search_company_tool(query: str) -> dict:\n'
    '    """Args: query - company name or ticker symbol."""\n'
    '    return await search_company(query)\n'
    '\n'
    '\n'
    '@mcp.tool(\n'
    '    name="get_filing",\n'
    '    description="Fetch recent SEC filings. Supports 10-K, 10-Q, 8-K, DEF 14A, S-1, 20-F.",\n'
    ')\n'
    'async def get_filing_tool(cik: str, form_type: str = "10-K", limit: int = 5) -> dict:\n'
    '    """Args: cik, form_type, limit (max 20)."""\n'
    '    return await get_filing(cik=cik, form_type=form_type, limit=limit)\n'
    '\n'
    '\n'
    '@mcp.tool(\n'
    '    name="get_financials",\n'
    '    description=(\n'
    '        "Retrieve structured financial data from XBRL-tagged SEC filings. "\n'
    '        "Covers income statement, balance sheet, and cash flow. "\n'
    '        "Free cash flow is computed as operating_cash_flow minus capex."\n'
    '    ),\n'
    ')\n'
    'async def get_financials_tool(\n'
    '    cik: str,\n'
    '    metrics: str = "income_statement",\n'
    '    period_type: str = "quarterly",\n'
    '    limit: int = 8,\n'
    ') -> dict:\n'
    '    """Args: cik, metrics, period_type, limit."""\n'
    '    return await get_financials(cik=cik, metrics=metrics, period_type=period_type, limit=limit)\n'
    '\n'
    '\n'
    '@mcp.tool(\n'
    '    name="compare_filings",\n'
    '    description="Compare financial metrics between two filing periods with absolute and % changes.",\n'
    ')\n'
    'async def compare_filings_tool(\n'
    '    cik: str,\n'
    '    period_a: str,\n'
    '    period_b: str,\n'
    '    metrics: str = "income_statement",\n'
    '    period_type: str = "quarterly",\n'
    ') -> dict:\n'
    '    """Args: cik, period_a (YYYY-MM), period_b (YYYY-MM), metrics, period_type."""\n'
    '    return await compare_filings(\n'
    '        cik=cik, period_a=period_a, period_b=period_b,\n'
    '        metrics=metrics, period_type=period_type,\n'
    '    )\n'
    '\n'
    '\n'
    'def main():\n'
    '    mcp.run()\n'
    '\n'
    '\n'
    'if __name__ == "__main__":\n'
    '    main()\n'
)

files["src/sec_edgar_mcp/tools/__init__.py"] = (
    'from .search_company import search_company\n'
    'from .get_filing import get_filing\n'
    'from .get_financials import get_financials\n'
    'from .compare_filings import compare_filings\n'
    '\n'
    '__all__ = ["search_company", "get_filing", "get_financials", "compare_filings"]\n'
)

files["src/sec_edgar_mcp/tools/search_company.py"] = (
    '"""\n'
    'Tool: search_company\n'
    'Resolves a company name or ticker to its SEC CIK identifier.\n'
    '"""\n'
    '\n'
    'from ..edgar_client import search_company_by_name, get_cik_from_ticker\n'
    '\n'
    '\n'
    'async def search_company(query: str) -> dict:\n'
    '    """\n'
    '    Search for a company by name or ticker and return its CIK.\n'
    '\n'
    '    Args:\n'
    '        query: Company name or ticker symbol\n'
    '    """\n'
    '    cik = await get_cik_from_ticker(query)\n'
    '    if cik:\n'
    '        return {\n'
    '            "resolved_via": "ticker",\n'
    '            "ticker": query.upper(),\n'
    '            "cik": cik,\n'
    '            "note": f"CIK resolved from ticker \'{query.upper()}\'. Use this CIK in other tools.",\n'
    '        }\n'
    '\n'
    '    results = await search_company_by_name(query)\n'
    '    if not results:\n'
    '        return {\n'
    '            "error": f"No companies found matching \'{query}\'.",\n'
    '            "suggestion": "Try a more specific name or use the ticker symbol directly.",\n'
    '        }\n'
    '\n'
    '    return {\n'
    '        "resolved_via": "name_search",\n'
    '        "query": query,\n'
    '        "matches": results,\n'
    '        "note": "Multiple matches found. Use the CIK of your intended company.",\n'
    '    }\n'
)

files["src/sec_edgar_mcp/tools/get_filing.py"] = (
    '"""\n'
    'Tool: get_filing\n'
    'Fetches recent SEC filings for a company by CIK and form type.\n'
    '"""\n'
    '\n'
    'from ..edgar_client import fetch_submissions\n'
    '\n'
    'SUPPORTED_FORMS = {"10-K", "10-Q", "8-K", "DEF 14A", "S-1", "20-F"}\n'
    '\n'
    '\n'
    'async def get_filing(cik: str, form_type: str = "10-K", limit: int = 5) -> dict:\n'
    '    """\n'
    '    Retrieve recent filings of a given form type for a company.\n'
    '\n'
    '    Args:\n'
    '        cik:       Company CIK\n'
    '        form_type: 10-K, 10-Q, 8-K, DEF 14A, S-1, 20-F\n'
    '        limit:     Number of filings to return (max 20)\n'
    '    """\n'
    '    if form_type not in SUPPORTED_FORMS:\n'
    '        return {\n'
    '            "error": f"Unsupported form type \'{form_type}\'.",\n'
    '            "supported_forms": sorted(SUPPORTED_FORMS),\n'
    '        }\n'
    '\n'
    '    limit = min(limit, 20)\n'
    '    submissions = await fetch_submissions(cik)\n'
    '    company_name = submissions.get("name", "Unknown")\n'
    '    recent = submissions.get("filings", {}).get("recent", {})\n'
    '\n'
    '    forms = recent.get("form", [])\n'
    '    accessions = recent.get("accessionNumber", [])\n'
    '    dates = recent.get("filingDate", [])\n'
    '    descriptions = recent.get("primaryDocument", [])\n'
    '\n'
    '    filings = []\n'
    '    for form, accession, date, doc in zip(forms, accessions, dates, descriptions):\n'
    '        if form == form_type:\n'
    '            accession_clean = accession.replace("-", "")\n'
    '            filing_url = (\n'
    '                f"https://www.sec.gov/Archives/edgar/data/{int(cik)}"\n'
    '                f"/{accession_clean}/{doc}"\n'
    '            )\n'
    '            filings.append({\n'
    '                "form_type": form,\n'
    '                "filing_date": date,\n'
    '                "accession_number": accession,\n'
    '                "primary_document": doc,\n'
    '                "filing_url": filing_url,\n'
    '            })\n'
    '        if len(filings) >= limit:\n'
    '            break\n'
    '\n'
    '    if not filings:\n'
    '        return {\n'
    '            "company": company_name,\n'
    '            "cik": cik,\n'
    '            "form_type": form_type,\n'
    '            "error": f"No {form_type} filings found.",\n'
    '        }\n'
    '\n'
    '    return {\n'
    '        "company": company_name,\n'
    '        "cik": cik,\n'
    '        "form_type": form_type,\n'
    '        "total_returned": len(filings),\n'
    '        "filings": filings,\n'
    '    }\n'
)

files["src/sec_edgar_mcp/tools/get_financials.py"] = (
    '"""\n'
    'Tool: get_financials\n'
    'Fetches structured financial data from SEC XBRL filings.\n'
    '"""\n'
    '\n'
    'from ..edgar_client import fetch_company_concept\n'
    '\n'
    'FINANCIAL_CONCEPTS = {\n'
    '    "revenue": ("us-gaap", "Revenues"),\n'
    '    "net_income": ("us-gaap", "NetIncomeLoss"),\n'
    '    "gross_profit": ("us-gaap", "GrossProfit"),\n'
    '    "operating_income": ("us-gaap", "OperatingIncomeLoss"),\n'
    '    "eps_basic": ("us-gaap", "EarningsPerShareBasic"),\n'
    '    "eps_diluted": ("us-gaap", "EarningsPerShareDiluted"),\n'
    '    "r_and_d": ("us-gaap", "ResearchAndDevelopmentExpense"),\n'
    '    "total_assets": ("us-gaap", "Assets"),\n'
    '    "total_liabilities": ("us-gaap", "Liabilities"),\n'
    '    "cash": ("us-gaap", "CashAndCashEquivalentsAtCarryingValue"),\n'
    '    "stockholders_equity": ("us-gaap", "StockholdersEquity"),\n'
    '    "long_term_debt": ("us-gaap", "LongTermDebt"),\n'
    '    "current_assets": ("us-gaap", "AssetsCurrent"),\n'
    '    "current_liabilities": ("us-gaap", "LiabilitiesCurrent"),\n'
    '    "operating_cash_flow": ("us-gaap", "NetCashProvidedByUsedInOperatingActivities"),\n'
    '    "capex": ("us-gaap", "PaymentsToAcquirePropertyPlantAndEquipment"),\n'
    '}\n'
    '\n'
    'METRIC_GROUPS = {\n'
    '    "income_statement": [\n'
    '        "revenue", "gross_profit", "operating_income",\n'
    '        "net_income", "eps_basic", "eps_diluted", "r_and_d",\n'
    '    ],\n'
    '    "balance_sheet": [\n'
    '        "total_assets", "current_assets", "cash",\n'
    '        "total_liabilities", "current_liabilities",\n'
    '        "long_term_debt", "stockholders_equity",\n'
    '    ],\n'
    '    "cash_flow": ["operating_cash_flow", "capex"],\n'
    '    "all": list(FINANCIAL_CONCEPTS.keys()),\n'
    '}\n'
    '\n'
    '\n'
    'def _filter_by_period(units: list[dict], period_type: str, limit: int) -> list[dict]:\n'
    '    if period_type == "annual":\n'
    '        filtered = [u for u in units if u.get("form") == "10-K"]\n'
    '    elif period_type == "quarterly":\n'
    '        filtered = [u for u in units if u.get("form") == "10-Q"]\n'
    '    else:\n'
    '        filtered = units\n'
    '    filtered.sort(key=lambda x: x.get("end", ""), reverse=True)\n'
    '    return filtered[:limit]\n'
    '\n'
    '\n'
    'async def get_financials(\n'
    '    cik: str,\n'
    '    metrics: str = "income_statement",\n'
    '    period_type: str = "quarterly",\n'
    '    limit: int = 8,\n'
    ') -> dict:\n'
    '    """\n'
    '    Retrieve structured financial data from XBRL-tagged SEC filings.\n'
    '\n'
    '    Args:\n'
    '        cik:         Company CIK\n'
    '        metrics:     income_statement | balance_sheet | cash_flow | all\n'
    '        period_type: quarterly or annual\n'
    '        limit:       Number of periods per metric (max 12)\n'
    '    """\n'
    '    limit = min(limit, 12)\n'
    '\n'
    '    if metrics in METRIC_GROUPS:\n'
    '        requested = METRIC_GROUPS[metrics]\n'
    '    else:\n'
    '        requested = [m.strip() for m in metrics.split(",")]\n'
    '        invalid = [m for m in requested if m not in FINANCIAL_CONCEPTS]\n'
    '        if invalid:\n'
    '            return {\n'
    '                "error": f"Unknown metric(s): {invalid}",\n'
    '                "available_metrics": list(FINANCIAL_CONCEPTS.keys()),\n'
    '                "available_groups": list(METRIC_GROUPS.keys()),\n'
    '            }\n'
    '\n'
    '    results = {}\n'
    '    errors = {}\n'
    '\n'
    '    for metric_name in requested:\n'
    '        taxonomy, tag = FINANCIAL_CONCEPTS[metric_name]\n'
    '        try:\n'
    '            data = await fetch_company_concept(cik, taxonomy, tag)\n'
    '            units_map = data.get("units", {})\n'
    '            raw_units = units_map.get("USD", units_map.get("USD/shares", []))\n'
    '            filtered = _filter_by_period(raw_units, period_type, limit)\n'
    '            results[metric_name] = [\n'
    '                {\n'
    '                    "period_end": u.get("end"),\n'
    '                    "period_start": u.get("start"),\n'
    '                    "value": u.get("val"),\n'
    '                    "form": u.get("form"),\n'
    '                    "filed": u.get("filed"),\n'
    '                }\n'
    '                for u in filtered\n'
    '            ]\n'
    '        except Exception as e:\n'
    '            errors[metric_name] = str(e)\n'
    '\n'
    '    if "operating_cash_flow" in results and "capex" in results:\n'
    '        ocf_by_period = {\n'
    '            e["period_end"]: e["value"]\n'
    '            for e in results["operating_cash_flow"]\n'
    '            if e["value"] is not None\n'
    '        }\n'
    '        fcf_series = []\n'
    '        for entry in results["capex"]:\n'
    '            period = entry["period_end"]\n'
    '            ocf = ocf_by_period.get(period)\n'
    '            if ocf is not None and entry["value"] is not None:\n'
    '                fcf_series.append({\n'
    '                    "period_end": period,\n'
    '                    "value": ocf - entry["value"],\n'
    '                    "form": entry["form"],\n'
    '                    "filed": entry["filed"],\n'
    '                    "note": "computed: operating_cash_flow - capex",\n'
    '                })\n'
    '        results["free_cash_flow"] = fcf_series\n'
    '\n'
    '    output = {\n'
    '        "cik": cik,\n'
    '        "metrics": metrics,\n'
    '        "period_type": period_type,\n'
    '        "data": results,\n'
    '    }\n'
    '    if errors:\n'
    '        output["errors"] = errors\n'
    '        output["note"] = "Some metrics unavailable via XBRL."\n'
    '    return output\n'
)

files["src/sec_edgar_mcp/tools/compare_filings.py"] = (
    '"""\n'
    'Tool: compare_filings\n'
    'Compares financial metrics across two periods for the same company.\n'
    '"""\n'
    '\n'
    'from .get_financials import get_financials\n'
    '\n'
    '\n'
    'def _find_period(data_series: list[dict], period_end: str):\n'
    '    for entry in data_series:\n'
    '        if entry.get("period_end", "").startswith(period_end[:7]):\n'
    '            return entry\n'
    '    return None\n'
    '\n'
    '\n'
    'def _compute_change(val_a: float, val_b: float) -> dict:\n'
    '    absolute = val_b - val_a\n'
    '    pct = round((absolute / abs(val_a)) * 100, 2) if val_a != 0 else None\n'
    '    return {\n'
    '        "period_a_value": val_a,\n'
    '        "period_b_value": val_b,\n'
    '        "absolute_change": round(absolute, 4),\n'
    '        "percent_change": pct,\n'
    '        "direction": "increase" if absolute > 0 else ("decrease" if absolute < 0 else "unchanged"),\n'
    '    }\n'
    '\n'
    '\n'
    'async def compare_filings(\n'
    '    cik: str,\n'
    '    period_a: str,\n'
    '    period_b: str,\n'
    '    metrics: str = "income_statement",\n'
    '    period_type: str = "quarterly",\n'
    ') -> dict:\n'
    '    """\n'
    '    Compare financial metrics between two filing periods.\n'
    '\n'
    '    Args:\n'
    '        cik:         Company CIK\n'
    '        period_a:    Earlier period end date (YYYY-MM)\n'
    '        period_b:    Later period end date (YYYY-MM)\n'
    '        metrics:     Same options as get_financials\n'
    '        period_type: quarterly or annual\n'
    '    """\n'
    '    financial_data = await get_financials(\n'
    '        cik=cik, metrics=metrics, period_type=period_type, limit=12\n'
    '    )\n'
    '    if "error" in financial_data:\n'
    '        return financial_data\n'
    '\n'
    '    raw_data = financial_data.get("data", {})\n'
    '    comparison = {}\n'
    '    missing_periods = {}\n'
    '\n'
    '    for metric_name, series in raw_data.items():\n'
    '        entry_a = _find_period(series, period_a)\n'
    '        entry_b = _find_period(series, period_b)\n'
    '\n'
    '        if entry_a is None or entry_b is None:\n'
    '            missing_periods[metric_name] = {\n'
    '                "period_a_found": entry_a is not None,\n'
    '                "period_b_found": entry_b is not None,\n'
    '                "available_periods": [e.get("period_end") for e in series],\n'
    '            }\n'
    '            continue\n'
    '\n'
    '        val_a = entry_a.get("value")\n'
    '        val_b = entry_b.get("value")\n'
    '        if val_a is None or val_b is None:\n'
    '            missing_periods[metric_name] = {"reason": "Null value in one or both periods"}\n'
    '            continue\n'
    '\n'
    '        change = _compute_change(float(val_a), float(val_b))\n'
    '        comparison[metric_name] = {\n'
    '            "period_a": {"end_date": entry_a.get("period_end"), "value": val_a},\n'
    '            "period_b": {"end_date": entry_b.get("period_end"), "value": val_b},\n'
    '            **change,\n'
    '        }\n'
    '\n'
    '    notable = sorted(\n'
    '        [(k, v) for k, v in comparison.items() if v.get("percent_change") is not None],\n'
    '        key=lambda x: abs(x[1]["percent_change"]),\n'
    '        reverse=True,\n'
    '    )[:5]\n'
    '\n'
    '    output = {\n'
    '        "cik": cik,\n'
    '        "period_a": period_a,\n'
    '        "period_b": period_b,\n'
    '        "metrics_compared": len(comparison),\n'
    '        "comparison": comparison,\n'
    '        "top_5_changes_by_magnitude": [\n'
    '            {"metric": k, "percent_change": v["percent_change"], "direction": v["direction"]}\n'
    '            for k, v in notable\n'
    '        ],\n'
    '    }\n'
    '    if missing_periods:\n'
    '        output["missing_or_unavailable"] = missing_periods\n'
    '    return output\n'
)

files["test_run.py"] = (
    'import asyncio\n'
    'import sys\n'
    'sys.path.insert(0, ".")\n'
    'from src.sec_edgar_mcp.tools import search_company, get_financials\n'
    '\n'
    '\n'
    'async def main():\n'
    '    print("Testing search_company...")\n'
    '    result = await search_company("AAPL")\n'
    '    print("CIK:", result["cik"])\n'
    '\n'
    '    print("\\nTesting get_financials...")\n'
    '    fin = await get_financials(\n'
    '        cik=result["cik"],\n'
    '        metrics="income_statement",\n'
    '        period_type="quarterly",\n'
    '        limit=4,\n'
    '    )\n'
    '    for entry in fin["data"]["revenue"]:\n'
    '        print(f\'  {entry["period_end"]}: ${entry["value"]:,.0f}\')\n'
    '\n'
    '\n'
    'asyncio.run(main())\n'
)

files["tests/test_tools.py"] = (
    '"""\n'
    'Tests for SEC EDGAR MCP tools.\n'
    'Run with: pytest tests/ -v\n'
    'Set SKIP_LIVE_TESTS=1 to skip network calls in CI.\n'
    '"""\n'
    '\n'
    'import os\n'
    'import pytest\n'
    '\n'
    'SKIP_LIVE = os.getenv("SKIP_LIVE_TESTS", "0") == "1"\n'
    'skip_if_no_network = pytest.mark.skipif(SKIP_LIVE, reason="Live network tests disabled")\n'
    '\n'
    'APPLE_TICKER = "AAPL"\n'
    'APPLE_CIK = "320193"\n'
    '\n'
    '\n'
    '@skip_if_no_network\n'
    '@pytest.mark.asyncio\n'
    'async def test_search_company_by_ticker():\n'
    '    from src.sec_edgar_mcp.tools import search_company\n'
    '    result = await search_company(APPLE_TICKER)\n'
    '    assert result["cik"] == APPLE_CIK\n'
    '    assert result["resolved_via"] == "ticker"\n'
    '\n'
    '\n'
    '@skip_if_no_network\n'
    '@pytest.mark.asyncio\n'
    'async def test_get_filing_10k():\n'
    '    from src.sec_edgar_mcp.tools import get_filing\n'
    '    result = await get_filing(cik=APPLE_CIK, form_type="10-K", limit=3)\n'
    '    assert result["form_type"] == "10-K"\n'
    '    assert len(result["filings"]) <= 3\n'
    '\n'
    '\n'
    '@pytest.mark.asyncio\n'
    'async def test_get_filing_unsupported_form():\n'
    '    from src.sec_edgar_mcp.tools import get_filing\n'
    '    result = await get_filing(cik=APPLE_CIK, form_type="FAKE-99")\n'
    '    assert "error" in result\n'
    '\n'
    '\n'
    '@skip_if_no_network\n'
    '@pytest.mark.asyncio\n'
    'async def test_get_financials_income_statement():\n'
    '    from src.sec_edgar_mcp.tools import get_financials\n'
    '    result = await get_financials(\n'
    '        cik=APPLE_CIK, metrics="income_statement",\n'
    '        period_type="quarterly", limit=4,\n'
    '    )\n'
    '    assert "revenue" in result["data"]\n'
    '\n'
    '\n'
    '@pytest.mark.asyncio\n'
    'async def test_get_financials_invalid_metric():\n'
    '    from src.sec_edgar_mcp.tools import get_financials\n'
    '    result = await get_financials(cik=APPLE_CIK, metrics="not_a_real_metric")\n'
    '    assert "error" in result\n'
    '\n'
    '\n'
    '@skip_if_no_network\n'
    '@pytest.mark.asyncio\n'
    'async def test_compare_filings_quarterly():\n'
    '    from src.sec_edgar_mcp.tools import compare_filings\n'
    '    result = await compare_filings(\n'
    '        cik=APPLE_CIK, period_a="2023-09", period_b="2024-09",\n'
    '        metrics="income_statement", period_type="quarterly",\n'
    '    )\n'
    '    assert "comparison" in result\n'
    '    assert "top_5_changes_by_magnitude" in result\n'
)

os.makedirs("src/sec_edgar_mcp/tools", exist_ok=True)
os.makedirs("tests", exist_ok=True)

for path, content in files.items():
    with open(path, "w", newline="\n") as f:
        f.write(content)
    print(f"  wrote {path}")

print("\nAll files rewritten. Now run:")
print("  pip install -r requirements.txt")
print("  python test_run.py")
